### ISSUE TITLE
MVP #1 User Auth Completed

### ISSUE THREAD

**Issue by dowinterfor6** [dowinterfor6/discourse#2]
1. User Authentication (new account creation, login, and demo login) (Finished ~1 day)

- Users can sign up, sign in, log out
  - Three users currently on the database (demo user is seeded in)
- Users can use a demo login to test features
  - Hardcoded in a user POJO with the demo username and password
- Users can't access servers and channels without an account
  - Use of AuthRoutes and ProtectedRoutes to redirect accordingly

2. Extra completions: 
- Errors on login/signup form
  - Uses HTML validations for basic validation
  - Displays invalid credentials as a custom message on login error
  - Displays model level validations as a custom message on signup error

**Comment by minucos** [comment]
Hi Andrew

User auth looks great! functionality is perfect, and love the errors messages.

Only a single note really:

- [ ] Add padding to top of navbar on splash page.

Happy for you to complete that anytime while doing your next MVP.

nice work.

Andy
